version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:10.15
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6a:78:0f:2d:57:a2:d1:83:1a:81:4e:af:76:d1:ff:31"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Show Git Author (Debug Env Vars)
          command: echo ${GIT_AUTHOR_NAME}
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - "*"

  lint:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint files
          command: yarn lint

  test:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run tests
          command: yarn test

  typecheck:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Check types
          command: yarn tsc

  publish:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Create builds
          command: yarn build

      - run:
          name: Publish new version
          command: yarn release

workflows:
  version: 2
  check-and-publish:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - typecheck:
          requires:
            - setup
      - publish:
          requires:
            - setup
            - lint
            - test
            - typecheck
          filters:
            branches:
              only: master
